### PR TITLE
fix: closes #37, fixes issue with two windows opening on click

### LINKED ISSUE #37: notification-list: when clicking the action link, two tabs/windows open on Firefox
When clicking the action link, two tabs/windows open. One tab is `void(0)` and the other tab is the `url` from the notification.

This behavior is seen in both the (latest) release and ESR. It doesn't behave this way in Chromium and Safari.

### PR DESCRIPTION
**Pull request by rmathis**
fixes issue with two windows opening on click

### CODE REVIEW

File: @uportal/notification-list/src/components/NotificationItem.vue [hunk 1]
```diff
@@ -31,9 +31,9 @@
                 </p>
                 <p class="media-link" v-if="notification.url">
                     <a
-                        href="javascript:void(0)"
+                        href=""
```
Comment (ChristianMurphy) [inline @uportal/notification-list/src/components/NotificationItem.vue]: will this force a page refresh? or will `preventDefault` catch this?

Comment (rmathis) [reply @uportal/notification-list/src/components/NotificationItem.vue]: preventDefault catches it. I need the href or the a tag doesn't get styled correctly.
